config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :select_quizzes
  resources :challenges
  resources :describe_quizzes
  resources :stages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api, { format: 'json' } do
    namespace :v1 do # バージョン1を表している
      resources :categories
      resources :users, only:[:index, :show]
      resources :stages, only:[:index, :show, :create] do
        resources :quizzes, only:[:index]
      end
      resources :describe_quizzes, only:[:index, :show]
      resources :challenges, only:[:create]

      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        registrations: 'api/v1/auth/registrations'
      }
      namespace :auth do
        resources :sessions, only: %i[index]
      end
    end
  end
end

app/controllers/select_quizzes_controller.rb
class SelectQuizzesController < ApplicationController
  before_action :set_select_quiz, only: %i[ show edit update destroy ]

  # GET /select_quizzes or /select_quizzes.json
  def index
    @select_quizzes = SelectQuiz.all
  end

  # GET /select_quizzes/1 or /select_quizzes/1.json
  def show
  end

  # GET /select_quizzes/new
  def new
    @select_quiz = SelectQuiz.new
  end

  # GET /select_quizzes/1/edit
  def edit
  end

  # POST /select_quizzes or /select_quizzes.json
  def create
    @select_quiz = SelectQuiz.new(select_quiz_params)

    respond_to do |format|
      if @select_quiz.save
        format.html { redirect_to select_quiz_url(@select_quiz), notice: "Select quiz was successfully created." }
        format.json { render :show, status: :created, location: @select_quiz }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @select_quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /select_quizzes/1 or /select_quizzes/1.json
  def update
    respond_to do |format|
      if @select_quiz.update(select_quiz_params)
        format.html { redirect_to select_quiz_url(@select_quiz), notice: "Select quiz was successfully updated." }
        format.json { render :show, status: :ok, location: @select_quiz }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @select_quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /select_quizzes/1 or /select_quizzes/1.json
  def destroy
    @select_quiz.destroy

    respond_to do |format|
      format.html { redirect_to select_quizzes_url, notice: "Select quiz was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_select_quiz
      @select_quiz = SelectQuiz.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def select_quiz_params
      params.require(:select_quiz).permit(:stage_id, :content, :image, :first_choice, :second_choice, :third_choice, :forth_choice, :answer_number)
    end
end

app/helpers/select_quizzes_helper.rb
module SelectQuizzesHelper
end

app/views/select_quizzes/_form.html.erb
<%= form_with(model: select_quiz) do |form| %>
  <% if select_quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(select_quiz.errors.count, "error") %> prohibited this select_quiz from being saved:</h2>

      <ul>
        <% select_quiz.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :stage_id %>
    <%= form.number_field :stage_id %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :first_choice %>
    <%= form.text_field :first_choice %>
  </div>

  <div class="field">
    <%= form.label :second_choice %>
    <%= form.text_field :second_choice %>
  </div>

  <div class="field">
    <%= form.label :third_choice %>
    <%= form.text_field :third_choice %>
  </div>

  <div class="field">
    <%= form.label :forth_choice %>
    <%= form.text_field :forth_choice %>
  </div>

  <div class="field">
    <%= form.label :answer_number %>
    <%= form.number_field :answer_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/select_quizzes/edit.html.erb
<h1>Editing Select Quiz</h1>

<%= render 'form', select_quiz: @select_quiz %>

<%= link_to 'Show', @select_quiz %> |
<%= link_to 'Back', select_quizzes_path %>

app/views/select_quizzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Select Quizzes</h1>

<table>
  <thead>
    <tr>
      <th>Stage</th>
      <th>Content</th>
      <th>Image</th>
      <th>First choice</th>
      <th>Second choice</th>
      <th>Third choice</th>
      <th>Forth choice</th>
      <th>Answer number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @select_quizzes.each do |select_quiz| %>
      <tr>
        <td><%= select_quiz.stage_id %></td>
        <td><%= select_quiz.content %></td>
        <td><%= select_quiz.image %></td>
        <td><%= select_quiz.first_choice %></td>
        <td><%= select_quiz.second_choice %></td>
        <td><%= select_quiz.third_choice %></td>
        <td><%= select_quiz.forth_choice %></td>
        <td><%= select_quiz.answer_number %></td>
        <td><%= link_to 'Show', select_quiz %></td>
        <td><%= link_to 'Edit', edit_select_quiz_path(select_quiz) %></td>
        <td><%= link_to 'Destroy', select_quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Select Quiz', new_select_quiz_path %>

app/views/select_quizzes/new.html.erb
<h1>New Select Quiz</h1>

<%= render 'form', select_quiz: @select_quiz %>

<%= link_to 'Back', select_quizzes_path %>

app/views/select_quizzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stage:</strong>
  <%= @select_quiz.stage_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @select_quiz.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= @select_quiz.image %>
</p>

<p>
  <strong>First choice:</strong>
  <%= @select_quiz.first_choice %>
</p>

<p>
  <strong>Second choice:</strong>
  <%= @select_quiz.second_choice %>
</p>

<p>
  <strong>Third choice:</strong>
  <%= @select_quiz.third_choice %>
</p>

<p>
  <strong>Forth choice:</strong>
  <%= @select_quiz.forth_choice %>
</p>

<p>
  <strong>Answer number:</strong>
  <%= @select_quiz.answer_number %>
</p>

<%= link_to 'Edit', edit_select_quiz_path(@select_quiz) %> |
<%= link_to 'Back', select_quizzes_path %>