config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :select_quizzes
  resources :challenges
  resources :describe_quizzes
  resources :stages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api, { format: 'json' } do
    namespace :v1 do # バージョン1を表している
      resources :categories
      resources :users, only:[:index, :show]
      resources :stages, only:[:index, :show, :create] do
        resources :quizzes, only:[:index]
      end
      resources :describe_quizzes, only:[:index, :show]
      resources :challenges, only:[:create]

      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        registrations: 'api/v1/auth/registrations'
      }
      namespace :auth do
        resources :sessions, only: %i[index]
      end
    end
  end
end

app/controllers/api/v1/describe_quizzes_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class DescribeQuizzesController < ApplicationController
      def index
        @describe_quizzes = DescribeQuiz.all
      end

      def show
        @quiz = DescribeQuiz.find(params[:id])
      end
    end
  end
end

app/controllers/describe_quizzes_controller.rb
# frozen_string_literal: true

class DescribeQuizzesController < ApplicationController
  before_action :set_describe_quiz, only: %i[show edit update destroy]

  # GET /describe_quizzes or /describe_quizzes.json
  def index
    @describe_quizzes = DescribeQuiz.all
  end

  # GET /describe_quizzes/1 or /describe_quizzes/1.json
  def show; end

  # GET /describe_quizzes/new
  def new
    @describe_quiz = DescribeQuiz.new
  end

  # GET /describe_quizzes/1/edit
  def edit; end

  # POST /describe_quizzes or /describe_quizzes.json
  def create
    @describe_quiz = DescribeQuiz.new(describe_quiz_params)

    respond_to do |format|
      if @describe_quiz.save
        format.html { redirect_to describe_quiz_url(@describe_quiz), notice: 'Describe quiz was successfully created.' }
        format.json { render :show, status: :created, location: @describe_quiz }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @describe_quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /describe_quizzes/1 or /describe_quizzes/1.json
  def update
    respond_to do |format|
      if @describe_quiz.update(describe_quiz_params)
        format.html { redirect_to describe_quiz_url(@describe_quiz), notice: 'Describe quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @describe_quiz }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @describe_quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /describe_quizzes/1 or /describe_quizzes/1.json
  def destroy
    @describe_quiz.destroy

    respond_to do |format|
      format.html { redirect_to describe_quizzes_url, notice: 'Describe quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_describe_quiz
    @describe_quiz = DescribeQuiz.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def describe_quiz_params
    params.require(:describe_quiz).permit(:stage_id, :image, :content)
  end
end

app/helpers/api/v1/describe_quizzes_helper.rb
# frozen_string_literal: true

module Api
  module V1
    module DescribeQuizzesHelper
    end
  end
end

app/helpers/describe_quizzes_helper.rb
# frozen_string_literal: true

module DescribeQuizzesHelper
end

app/views/describe_quizzes/_form.html.erb
<%= form_with(model: describe_quiz) do |form| %>
  <% if describe_quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(describe_quiz.errors.count, "error") %> prohibited this describe_quiz from being saved:</h2>

      <ul>
        <% describe_quiz.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :stage_id %>
    <%= form.text_field :stage_id %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/describe_quizzes/edit.html.erb
<h1>Editing Describe Quiz</h1>

<%= render 'form', describe_quiz: @describe_quiz %>

<%= link_to 'Show', @describe_quiz %> |
<%= link_to 'Back', describe_quizzes_path %>

app/views/describe_quizzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Describe Quizzes</h1>

<table>
  <thead>
    <tr>
      <th>Stage</th>
      <th>Image</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @describe_quizzes.each do |describe_quiz| %>
      <tr>
        <td><%= describe_quiz.stage_id %></td>
        <td><%= describe_quiz.image %></td>
        <td><%= describe_quiz.content %></td>
        <td><%= link_to 'Show', describe_quiz %></td>
        <td><%= link_to 'Edit', edit_describe_quiz_path(describe_quiz) %></td>
        <td><%= link_to 'Destroy', describe_quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Describe Quiz', new_describe_quiz_path %>

app/views/describe_quizzes/new.html.erb
<h1>New Describe Quiz</h1>

<%= render 'form', describe_quiz: @describe_quiz %>

<%= link_to 'Back', describe_quizzes_path %>

app/views/describe_quizzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stage:</strong>
  <%= @describe_quiz.stage_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @describe_quiz.image %>
</p>

<p>
  <strong>Content:</strong>
  <%= @describe_quiz.content %>
</p>

<%= link_to 'Edit', edit_describe_quiz_path(@describe_quiz) %> |
<%= link_to 'Back', describe_quizzes_path %>