config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :select_quizzes
  resources :challenges
  resources :describe_quizzes
  resources :stages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api, { format: 'json' } do
    namespace :v1 do # バージョン1を表している
      resources :categories
      resources :users, only:[:index, :show]
      resources :stages, only:[:index, :show, :create] do
        resources :quizzes, only:[:index]
      end
      resources :describe_quizzes, only:[:index, :show]
      resources :challenges, only:[:create]

      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        registrations: 'api/v1/auth/registrations'
      }
      namespace :auth do
        resources :sessions, only: %i[index]
      end
    end
  end
end

app/models/stage.rb
# frozen_string_literal: true

class Stage < ApplicationRecord
  belongs_to :user
  validates :name, presence: true, length: { minimum: 1, maximum: 30 }
  validates :description, presence: true, length: { minimum: 1, maximum: 30 }
  validates :image, presence: true
  mount_uploader :image, ImageUploader
  has_many :describe_quizzes, dependent: :destroy
  has_many :select_quizzes, dependent: :destroy

  def quiz; end
end

app/controllers/api/v1/stages_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class StagesController < ApplicationController
      def index
        @stages = Stage.all
      end

      def create
        @stage = Stage.new(stage_params)
        if @stage.save
          render json: { status: 'SUCCESS', data: @stage }
        else
          render json: { status: 'ERROR', data: @stage.errors }
        end
      end

      def show
        @stage = Stage.find(params[:id])
      end

      private

      def stage_params
        params.require(:stage).permit(:user_id, :name, :description, :image, :is_public)
      end
    end
  end
end

app/controllers/stages_controller.rb
# frozen_string_literal: true

class StagesController < ApplicationController
  before_action :set_stage, only: %i[show edit update destroy]

  # GET /stages or /stages.json
  def index
    @stages = Stage.all
  end

  # GET /stages/1 or /stages/1.json
  def show
    @quizzes = @stage.describe_quizzes + @stage.select_quizzes
  end

  # GET /stages/new
  def new
    @stage = Stage.new
  end

  # GET /stages/1/edit
  def edit; end

  # POST /stages or /stages.json
  def create
    @stage = Stage.new(stage_params)

    respond_to do |format|
      if @stage.save
        format.html { redirect_to stage_url(@stage), notice: 'Stage was successfully created.' }
        format.json { render :show, status: :created, location: @stage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stages/1 or /stages/1.json
  def update
    respond_to do |format|
      if @stage.update(stage_params)
        format.html { redirect_to stage_url(@stage), notice: 'Stage was successfully updated.' }
        format.json { render :show, status: :ok, location: @stage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stages/1 or /stages/1.json
  def destroy
    @stage.destroy

    respond_to do |format|
      format.html { redirect_to stages_url, notice: 'Stage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_stage
    @stage = Stage.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def stage_params
    params.require(:stage).permit(:user_id, :name, :description, :image, :is_public)
  end
end

app/helpers/api/v1/stages_helper.rb
# frozen_string_literal: true

module Api
  module V1
    module StagesHelper
    end
  end
end

app/helpers/stages_helper.rb
# frozen_string_literal: true

module StagesHelper
end

app/views/stages/_form.html.erb
<%= form_with(model: stage) do |form| %>
  <% if stage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stage.errors.count, "error") %> prohibited this stage from being saved:</h2>

      <ul>
        <% stage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :is_public %>
    <%= form.check_box :is_public %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stages/edit.html.erb
<h1>Editing Stage</h1>

<%= render 'form', stage: @stage %>

<%= link_to 'Show', @stage %> |
<%= link_to 'Back', stages_path %>

app/views/stages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stages</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th>Is public</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stages.each do |stage| %>
      <tr>
        <td><%= stage.user_id %></td>
        <td><%= stage.name %></td>
        <td><%= stage.description %></td>
        <td><%= stage.image %></td>
        <td><%= stage.is_public %></td>
        <td><%= link_to 'Show', stage %></td>
        <td><%= link_to 'Edit', edit_stage_path(stage) %></td>
        <td><%= link_to 'Destroy', stage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stage', new_stage_path %>

app/views/stages/new.html.erb
<h1>New Stage</h1>

<%= render 'form', stage: @stage %>

<%= link_to 'Back', stages_path %>

app/views/stages/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Stage#<%= @stage.id %></h1>
<p>
  <strong>User:</strong>
  <%= @stage.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @stage.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @stage.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @stage.image %>
</p>

<p>
  <strong>Is public:</strong>
  <%= @stage.is_public %>
</p>

<%= link_to 'Edit', edit_stage_path(@stage) %> |
<%= link_to 'Back', stages_path %>

<p id="notice"><%= notice %></p>

<h2>Describe Quizzes</h2>

<table>
  <thead>
    <tr>
      <th>Stage</th>
      <th>Image</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |describe_quiz| %>
      <tr>
        <td><%= describe_quiz.stage_id %></td>
        <td><%= describe_quiz.image %></td>
        <td><%= describe_quiz.content %></td>
        <td><%= link_to 'Show', describe_quiz %></td>
        <td><%= link_to 'Edit', edit_describe_quiz_path(describe_quiz) %></td>
        <td><%= link_to 'Destroy', describe_quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Describe Quiz', new_describe_quiz_path %>