config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :select_quizzes
  resources :challenges
  resources :describe_quizzes
  resources :stages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api, { format: 'json' } do
    namespace :v1 do # バージョン1を表している
      resources :categories
      resources :users, only:[:index, :show]
      resources :stages, only:[:index, :show, :create] do
        resources :quizzes, only:[:index]
      end
      resources :describe_quizzes, only:[:index, :show]
      resources :challenges, only:[:create]

      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        registrations: 'api/v1/auth/registrations'
      }
      namespace :auth do
        resources :sessions, only: %i[index]
      end
    end
  end
end

app/models/challenge.rb
# frozen_string_literal: true

class Challenge < ApplicationRecord
  belongs_to :user
  belongs_to :stage

  validates :content, presence: true, length: { minimum: 2, maximum: 100 }, if: :image_nil?
  validates :image, presence: true, if: :content_nil?
  validates :first_choice, presence: true, length: { minimum: 2, maximum: 100 }
  validates :second_choice, presence: true, length: { minimum: 2, maximum: 100 }
  validates :third_choice, presence: true, length: { minimum: 2, maximum: 100 }
  validates :forth_choice, presence: true, length: { minimum: 2, maximum: 100 }
  validates :answer, presence: true, numericality: { in: 1..4 }
end

app/controllers/api/v1/challenges_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ChallengesController < ApplicationController
      def create
        @challenge = Challenge.new(challenge_params)

        if @challenge.save
          render json: { status: 'SUCCESS', data: @challenge }
        else
          render json: { status: 'ERROR', data: @challenge.errors }
        end
      end

      private

      def challenge_params
        params.require(:challenge).permit(:stage_id, :user_id)
      end
    end
  end
end

app/controllers/challenges_controller.rb
# frozen_string_literal: true

class ChallengesController < ApplicationController
  before_action :set_challenge, only: %i[show edit update destroy]

  # GET /challenges or /challenges.json
  def index
    @challenges = Challenge.all
  end

  # GET /challenges/1 or /challenges/1.json
  def show; end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit; end

  # POST /challenges or /challenges.json
  def create
    @challenge = Challenge.new(challenge_params)

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to challenge_url(@challenge), notice: 'Challenge was successfully created.' }
        format.json { render :show, status: :created, location: @challenge }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1 or /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to challenge_url(@challenge), notice: 'Challenge was successfully updated.' }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1 or /challenges/1.json
  def destroy
    @challenge.destroy

    respond_to do |format|
      format.html { redirect_to challenges_url, notice: 'Challenge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_challenge
    @challenge = Challenge.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def challenge_params
    params.require(:challenge).permit(:user_id, :stage_id, :hp, :score)
  end
end

app/helpers/api/v1/challenges_helper.rb
# frozen_string_literal: true

module Api
  module V1
    module ChallengesHelper
    end
  end
end

app/helpers/challenges_helper.rb
# frozen_string_literal: true

module ChallengesHelper
end

app/views/challenges/_form.html.erb
<%= form_with(model: challenge) do |form| %>
  <% if challenge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(challenge.errors.count, "error") %> prohibited this challenge from being saved:</h2>

      <ul>
        <% challenge.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :stage_id %>
    <%= form.text_field :stage_id %>
  </div>

  <div class="field">
    <%= form.label :hp %>
    <%= form.number_field :hp %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/challenges/edit.html.erb
<h1>Editing Challenge</h1>

<%= render 'form', challenge: @challenge %>

<%= link_to 'Show', @challenge %> |
<%= link_to 'Back', challenges_path %>

app/views/challenges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Challenges</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>User name</th>
      <th>Stage</th>
      <th>Stage name</th>
      <th>Hp</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @challenges.each do |challenge| %>
      <tr>
        <td><%= challenge.user_id %></td>
        <td><%= challenge.user.name %></td>
        <td><%= challenge.stage_id %></td>
        <td><%= challenge.stage.name %></td>
        <td><%= challenge.hp %></td>
        <td><%= challenge.score %></td>
        <td><%= link_to 'Show', challenge %></td>
        <td><%= link_to 'Edit', edit_challenge_path(challenge) %></td>
        <td><%= link_to 'Destroy', challenge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Challenge', new_challenge_path %>

app/views/challenges/new.html.erb
<h1>New Challenge</h1>

<%= render 'form', challenge: @challenge %>

<%= link_to 'Back', challenges_path %>

app/views/challenges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @challenge.user_id %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @challenge.stage_id %>
</p>

<p>
  <strong>Hp:</strong>
  <%= @challenge.hp %>
</p>

<p>
  <strong>Score:</strong>
  <%= @challenge.score %>
</p>

<%= link_to 'Edit', edit_challenge_path(@challenge) %> |
<%= link_to 'Back', challenges_path %>